source.. = src/
output.. = bin/
bin.includes = plugin.xml,\
               META-INF/,\
               OSGI-INF/,\
               .,\
               icons/,\
               plugin.properties,\
               plugin_ru_RU.properties,\
               .settings/,\
               src/
